services:
  database:
    container_name: mongodb
    image: mongo:6.0-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - btd_storage:/data/db
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    volumes:
      - btd_storage:/data
    ports:
      - ${REDIS_PORT}:6379
volumes:
  btd_storage:
